# Datasources
Python Notebook for exploring and analyzing the datasources used in this project

## Setup
### Install Dependencies

In [51]:
%pip install pandas
%pip install openpyxl

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in /Users/niklas/Library/Python/3.11/lib/python/site-packages (2.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/niklas/Library/Python/3.11/lib/python/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/niklas/Library/Python/3.11/lib/python/site-packages (from pandas) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in /Users/niklas/Library/Python/3.11/lib/python/site-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.21.0 in /Users/niklas/Library/Python/3.11/lib/python/site-packages (from pandas) (1.24.2)
Requirement already satisfied: six>=1.5 in /Users/niklas/Library/Python/3.11/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

[notice] A new release of pip is available: 23.1 -> 23.1.2
[notice] To update, run: python3 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: openpyxl in /Users/niklas/Library/Python/3.11/lib/python/site-packages (3.1.2)
Requirement already satisfied: et-xmlfile in /Users/niklas/Library/Python/3.11/lib/python/site-packages (from openpyxl) (1.1.0)

[notice] A new release of pip is available: 23.1 -> 23.1.2
[notice] To update, run: python3 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

### Import Packages

In [52]:
import pandas as pd

## Datasource1: Charging Infrastructure

### Load and Clean the Data

In [53]:
data_path = 'https://www.bundesnetzagentur.de/SharedDocs/Downloads/DE/Sachgebiete/Energie/Unternehmen_Institutionen/E_Mobilitaet/Ladesaeuleninfrastruktur.xlsx?__blob=publicationFile'

# Load the excel sheet
ds1 = pd.read_excel(data_path,
                    sheet_name='4.1 Ladepunkte je BL',
                    header=[6, 7],
                    index_col=4)

# Drop unimportant rows and columns
ds1 = ds1.iloc[:-1, 4:]

# Assign index and column names
ds1.columns.names = ['Date', 'Type']
ds1.index.name = 'State'

# Overview of the cleaned table
ds1

Date                   2017-01-01                2017-04-01
Type                          NLP    SLP  gesamt        NLP    SLP  gesamt
State
Baden-WÃ¼rttemberg           701.0  140.0   841.0      752.0  160.0   912.0  \
Bayern                     1348.0  156.0  1504.0     1504.0  171.0  1675.0
Berlin                      493.0   16.0   509.0      520.0   20.0   540.0
Brandenburg                  38.0    6.0    44.0       39.0    8.0    47.0
Bremen                        8.0    0.0     8.0       16.0    0.0    16.0
Hamburg                     315.0   13.0   328.0      378.0   18.0   396.0
Hessen                      366.0   45.0   411.0      419.0   45.0   464.0
Mecklenburg-Vorpommern       58.0   10.0    68.0       58.0   10.0    68.0
Niedersachsen               496.0   57.0   553.0      522.0   63.0   585.0
Nordrhein-Westfalen        1275.0   48.0  1323.0     1361.0   50.0  1411.0
Rheinland-Pfalz             177.0   28.0   205.0      188.0   30.0   218.0
Saarland                     16.0    0.0    16.0       18.0    0.0    18.0
Sachsen                     197.0   12.0   209.0      206.0   12.0   218.0
Sachsen-Anhalt               52.0   32.0    84.0       57.0   34.0    91.0
Schleswig-Holstein          233.0   26.0   259.0      328.0   31.0   359.0
ThÃ¼ringen                    91.0   21.0   112.0      116.0   25.0   141.0
Summe                      5864.0  610.0  6474.0     6482.0  677.0  7159.0

Date                   2017-07-01                2017-10-01  ... 2022-04-01
Type                          NLP    SLP  gesamt        NLP  ...     gesamt
State                                                        ...
Baden-WÃ¼rttemberg           781.0  177.0   958.0      875.0  ...    11042.0  \
Bayern                     1613.0  188.0  1801.0     1866.0  ...    13711.0
Berlin                      547.0   20.0   567.0      595.0  ...     1987.0
Brandenburg                  50.0    8.0    58.0       68.0  ...     1413.0
Bremen                       44.0    0.0    44.0       65.0  ...      416.0
Hamburg                     428.0   24.0   452.0      548.0  ...     1686.0
Hessen                      493.0   62.0   555.0      598.0  ...     5008.0
Mecklenburg-Vorpommern       62.0   15.0    77.0       84.0  ...      802.0
Niedersachsen               651.0   80.0   731.0      747.0  ...     6513.0
Nordrhein-Westfalen        1439.0   60.0  1499.0     1528.0  ...    11561.0
Rheinland-Pfalz             201.0   32.0   233.0      237.0  ...     2498.0
Saarland                     18.0    0.0    18.0       28.0  ...      555.0
Sachsen                     212.0   22.0   234.0      229.0  ...     2657.0
Sachsen-Anhalt               69.0   39.0   108.0       95.0  ...     1123.0
Schleswig-Holstein          365.0   35.0   400.0      409.0  ...     2837.0
ThÃ¼ringen                   132.0   31.0   163.0      199.0  ...     1290.0
Summe                      7105.0  793.0  7898.0     8171.0  ...    65099.0

Date                   2022-07-01                   2022-10-01
Type                          NLP      SLP   gesamt        NLP      SLP
State
Baden-WÃ¼rttemberg         10207.0   1698.0  11905.0    11171.0   1872.0  \
Bayern                    12629.0   1963.0  14592.0    13361.0   2177.0
Berlin                     1785.0    248.0   2033.0     1774.0    263.0
Brandenburg                1203.0    300.0   1503.0     1256.0    325.0
Bremen                      390.0     54.0    444.0      409.0     58.0
Hamburg                    1567.0    224.0   1791.0     1630.0    249.0
Hessen                     4680.0    713.0   5393.0     5041.0    788.0
Mecklenburg-Vorpommern      683.0    179.0    862.0      726.0    214.0
Niedersachsen              5750.0   1251.0   7001.0     6166.0   1356.0
Nordrhein-Westfalen       10713.0   1765.0  12478.0    11691.0   1992.0
Rheinland-Pfalz            1964.0    646.0   2610.0     2168.0    691.0
Saarland                    505.0     79.0    584.0      538.0     85.0
Sachsen                    2355.0    504.0   2859.0     2476.0    555.0
Sachsen-Anhalt              874.0    292.0   1166.0      920.0    339.0
Schleswig-Holstein         2496.0    496.0   2992.0     2608.0    536.0
ThÃ¼ringen                   986.0    351.0   1337.0     1073.0    382.0
Summe                     58787.0  10763.0  69550.0    63008.0  11882.0

Date                            2023-01-01
Type                     gesamt        NLP      SLP   gesamt
State
Baden-WÃ¼rttemberg       13043.0    12635.0   2093.0  14728.0
Bayern                  15538.0    14456.0   2391.0  16847.0
Berlin                   2037.0     1925.0    335.0   2260.0
Brandenburg              1581.0     1323.0    352.0   1675.0
Bremen                    467.0      514.0     60.0    574.0
Hamburg                  1879.0     1787.0    289.0   2076.0
Hessen                   5829.0     5410.0    885.0   6295.0
Mecklenburg-Vorpommern    940.0      769.0    220.0    989.0
Niedersachsen            7522.0     6657.0   1436.0   8093.0
Nordrhein-Westfalen     13683.0    12733.0   2193.0  14926.0
Rheinland-Pfalz          2859.0     2343.0    775.0   3118.0
Saarland                  623.0      561.0     93.0    654.0
Sachsen                  3031.0     2669.0    596.0   3265.0
Sachsen-Anhalt           1259.0      951.0    355.0   1306.0
Schleswig-Holstein       3144.0     2786.0    571.0   3357.0
ThÃ¼ringen                1455.0     1140.0    429.0   1569.0
Summe                   74890.0    68659.0  13073.0  81732.0

[17 rows x 75 columns]

## Datasource2.1: New Registrations of Motor Vehicles with Alternative Drive Systems over Time

### Load and Clean the Data

In [54]:
data_path = 'https://www.kba.de/SharedDocs/Downloads/DE/Statistik/Fahrzeuge/FZ28/fz28_2023_03.xlsx?__blob=publicationFile'

# Load the excel sheet
ds2_1 = pd.read_excel(data_path,
                      sheet_name='FZ 28.2',
                      header=None,
                      index_col=1)

# Drop unimportant rows and columns
ds2_1 = ds2_1.iloc[12:107, [1, 4]]

# Rename the columns
ds2_1.columns = ['Overall', 'Electric drives']

# Just take the rows for the annual amounts
ds2_1 = ds2_1.loc[list(filter(lambda i: 'Jahr' in i,  ds2_1.index))]

# Rename the index values 
idx = pd.Index(map(lambda i: int(i.split(' ')[1]), ds2_1.index))
idx.name = 'Year'
ds2_1.index = idx

# Drop year 2023
ds2_1 = ds2_1.drop(2023)

# Overview of the cleaned table
ds2_1

      Overall Electric drives
Year
2022  2651357          833487
2021  2622132          681874
2020  2917678          394940
2019  3607258          108837
2018  3435778           67655
2017  3441262           54612
2016  3351607           25203

## Datasource2.2: New Registrations of Motor Vehivles with Alternative Drive Systems by German States

### Load and Clean the Data

In [55]:
year = 2022
data_path = f'https://www.kba.de/SharedDocs/Downloads/DE/Statistik/Fahrzeuge/FZ28/fz28_{year}_12.xlsx?__blob=publicationFile'

# Load the excel sheet
ds2_1 = pd.read_excel(data_path,
                      sheet_name='FZ 28.9',
                      header=None,
                      index_col=1)

# Drop unimportant rows and columns
ds2_1 = ds2_1.iloc[30:47, [1, 4]]

# Rename the columns
ds2_1.columns = ['Overall', 'Electric drives']

# Rename the first index value
idx = list(ds2_1.index)
idx[0] = 'Gesamt'
ds2_1.index = idx

# Assign index name
ds2_1.index.name = 'State'

# Overview of the cleaned table
ds2_1

                        Overall Electric drives
State
Gesamt                  2651357          833487
Baden-WÃ¼rttemberg        367051          128965
Bayern                   549542          165969
Berlin                    66204           19907
Brandenburg               49331           14521
Bremen                    15665            4718
Hamburg                   84411           20174
Hessen                   279749           88373
Mecklenburg-Vorpommern    27668            6670
Niedersachsen            265906           76852
Nordrhein-Westfalen      557741          188857
Rheinland-Pfalz          107903           39555
Saarland                  31590           10505
Sachsen                   85823           20156
Sachsen-Anhalt            43914           10130
Schleswig-Holstein        69991           25710
ThÃ¼ringen                 47606           11996

## Datasource3: German States with Capitals by Area, Population and Population Density

### Load and Clean the Data
From this data source, we are only interested in the area for the states, so the other columns and rows are gonna be cleaned out

In [56]:
data_path = 'https://www.destatis.de/DE/Themen/Laender-Regionen/Regionales/Gemeindeverzeichnis/Administrativ/02-bundeslaender.xlsx?__blob=publicationFile'

# Load the excel sheet
ds3 = pd.read_excel(data_path,
                    sheet_name='BundeslÃ¤nder_mit_HauptstÃ¤dten',
                    usecols=[0,2],
                    header=None,
                    index_col=None)

# Drop unimportant rows
ds3 = ds3.iloc[7:-16]

# Rename the columns
ds3.columns = ['State', 'Area']

# Remove the number from each state name
ds3['State'] = ds3['State'].apply(lambda x: x[4:] if type(x) is str else x)

# 
ds3.iloc[-1, 0] = 'Gesamt'

# Drop the rows which contain NaN (= rows for the states capitals)
ds3 = ds3.dropna()

# Set the State column as the index
ds3.set_index('State', inplace=True)

# Overview of the cleaned table
ds3

                             Area
State
Schleswig-Holstein        15804.3
Hamburg                    755.09
Niedersachsen            47709.86
Bremen                     419.37
Nordrhein-Westfalen      34112.61
Hessen                   21115.63
Rheinland-Pfalz          19857.97
Baden-WÃ¼rttemberg        35747.85
Bayern                   70541.58
Saarland                  2571.52
Berlin                     891.12
Brandenburg              29654.37
Mecklenburg-Vorpommern    23294.9
Sachsen                  18449.89
Sachsen-Anhalt           20464.04
ThÃ¼ringen                16202.39
Gesamt                  357592.49